sudo: requried
language: generic

services: docker

before_install:
  - docker build -t mrtnc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mrtnc/react-test npm test

after_success:
  - docker build -t mrtnc014/multi-client ./client
  - docker build -t mrtnc014/multi-nginx ./nginx
  - docker build -t mrtnc014/multi-server ./server
  - docker build -t mrtnc014/multi-worker ./worker

  #docker login 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take image to docker hub
  - docker push mrtnc014/multi-client
  - docker push mrtnc014/multi-nginx
  - docker push mrtnc014/multi-server
  - docker push mrtnc014/multi-worker

deploy:
  provider: 'elasticbeanstalk'
  region: 'ap-southeast-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-180601101029'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY